import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {chromium} from 'playwright';
import {startStaticServer} from './lib/static-server.mjs';
import {test as registerTest,runAll,formatResults} from './lib/harness.mjs';
import {annualRows,expectedOrder,flowValue,groupIndex,hashes} from './lib/sorting-expected.mjs';
const filter=process.env.TABLE_FILTER?new RegExp(process.env.TABLE_FILTER):null;
function test(name,fn){if(!filter||filter.test(name))registerTest(name,fn);}
const live=process.env.BASE_URL,server=live?null:await startStaticServer(),base=live?live.replace(/\/?$/,'/'):server.baseUrl;
const output=process.env.TEST_REPORT_DIR??`reports/tests/table-sorting/${live?'live':'local'}`;fs.mkdirSync(output,{recursive:true});
const browser=await chromium.launch(),errors=[],checks=[];
const configs=[
 {kind:'home',route:'?year=2013',selector:'.home-ranking-table',id:'code',columns:{Rank:'rank',Partner:'name',Imports:'imports',Exports:'exports',Balance:'balance','Total trade value':'total_trade_value'},csv:'home'},
 {kind:'section',route:'section/XVI?year=2013',selector:'.section-page table',id:'code',columns:{Rank:'rank',Partner:'name',Kind:'kind',Imports:'imports',Exports:'exports',Balance:'balance','Total trade value':'total_trade_value'},csv:'section'},
 {kind:'years',route:'partner/6022?year=2013&section=I',selector:'.partner-years-table',id:'year',columns:{Year:'year',Imports:'imports',Exports:'exports',Balance:'balance','Total trade value':'total_trade_value'},code:'6022'},
 {kind:'groups',route:'partner/7530?year=2013&section=I',selector:'.partner-groups-table',id:'section_id',columns:{'Group order':'group',Imports:'imports',Exports:'exports','Total trade value':'total_trade_value'},code:'7530'},
 {kind:'chapters',route:'partner/7530?year=2013&section=I',selector:'.partner-chapters-table',id:'chapter',columns:{Chapter:'chapter',Description:'description',Imports:'imports',Exports:'exports','Total trade value':'total_trade_value'},code:'7530'}];
async function withPage(fn,viewport={width:1280,height:900}){const context=await browser.newContext({viewport,acceptDownloads:true});const page=await context.newPage();page.setDefaultTimeout(10000);const own=[];page.on('pageerror',e=>own.push(e.message));page.on('console',m=>{if(m.type()==='error')own.push(m.text());});try{const out=await fn(page);assert.deepEqual(own,[]);return out;}finally{errors.push(...own);await context.close();}}
async function go(page,route){const r=await page.goto(base+route,{waitUntil:'networkidle'});assert.equal(r.status(),200);}
function header(table,label){return table.locator('thead th').filter({has:table.page().getByRole('button',{name:new RegExp(`^${label}: sort `)})});}
async function setSort(table,label,direction,keyboard=false){const th=header(table,label),wanted=direction==='asc'?'ascending':'descending';if(await th.getAttribute('aria-sort')===wanted)await th.getByRole('button').click();if(await th.getAttribute('aria-sort')!==wanted){const button=th.getByRole('button');if(keyboard){await button.focus();await button.press('Enter');}else await button.click();if(await th.getAttribute('aria-sort')!==wanted)await button.click();}assert.equal(await th.getAttribute('aria-sort'),wanted);assert.equal(await table.locator('thead th[aria-sort="ascending"],thead th[aria-sort="descending"]').count(),1);}
async function rowIds(table,kind){if(kind==='home'||kind==='section')return table.locator('tbody tr a[href*="/partner/"]').evaluateAll(a=>a.map(e=>e.getAttribute('href').match(/partner\/([^/?]+)/)[1]));if(kind==='groups')return table.locator('tbody tr .group-button').evaluateAll(a=>a.map(e=>e.textContent.split(':')[0].trim()));return table.locator('tbody tr > :first-child').evaluateAll(a=>a.map(e=>e.textContent.replace('*','').trim()));}
function parseCsv(text){const rows=[];let row=[],v='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){v+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(v);v='';}else if(c==='\n'&&!q){row.push(v.replace(/\r$/,''));rows.push(row);row=[];v='';}else v+=c;}const h=rows.shift();return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])));}
async function exportRows(page,table,kind){const btn=kind==='home'?page.getByRole('button',{name:'Download all partners CSV',exact:true}):table.locator('xpath=ancestor::section[1]').getByRole('button',{name:'Download CSV',exact:true});const pending=page.waitForEvent('download');await btn.click();const d=await pending;return parseCsv(fs.readFileSync(await d.path(),'utf8'));}
function expected(rows,config,key,dir,metric='total_trade_value'){
 let ranks;if(key==='rank'){const sorted=expectedOrder(rows,r=>flowValue(r,metric),r=>r[config.id],'desc');ranks=new Map(sorted.map((r,i)=>[r[config.id],flowValue(r,metric)===null?null:i+1]));}
 const value=r=>key==='rank'?ranks.get(r[config.id]):key==='group'?groupIndex(r.section_id):flowValue(r,key);
 return expectedOrder(rows,value,r=>r[config.id],dir).map(r=>String(r[config.id]));
}
const chartPaths=async page=>{await page.mouse.move(0,0);return page.locator('.recharts-line-curve,.recharts-bar-rectangle path').evaluateAll(a=>a.map(e=>e.getAttribute('d')));};
function assertCharts(actual,expected){assert.equal(actual.length,expected.length);for(let i=0;i<actual.length;i++){const tokenize=s=>s.match(/[a-zA-Z]|[-+]?(?:\d*\.)?\d+(?:e[-+]?\d+)?/g);const a=tokenize(actual[i]),b=tokenize(expected[i]);assert.equal(a.length,b.length);for(let j=0;j<a.length;j++){if(Number.isNaN(Number(a[j]))||Number.isNaN(Number(b[j])))assert.equal(a[j],b[j]);else assert.ok(Math.abs(Number(a[j])-Number(b[j]))<=1e-8,`Chart coordinate ${i}/${j} changed`);}}}
for(const config of configs)test(`${config.kind}: every column both directions matches exact input and CSV order`,()=>withPage(async page=>{
 await go(page,config.route);const table=page.locator(config.selector),rows=annualRows(config.kind,config.code,2013,'I');if(config.kind==='home')await page.getByRole('button',{name:/Show all/}).click();
 const initialCharts=await chartPaths(page),totals=await page.locator('.world-total-card').allTextContents();
 assert.equal(await table.locator('thead button').count(),Object.keys(config.columns).length);
 for(const [label,key]of Object.entries(config.columns))for(const direction of ['asc','desc']){
  await setSort(table,label,direction);const params=new URL(page.url()).searchParams;assert.equal(params.get(`${config.kind}_sort`),key);assert.equal(params.get(`${config.kind}_dir`),direction);
  const order=expected(rows,config,key,direction,params.get('rank')??'total_trade_value');assert.deepEqual(await rowIds(table,config.kind),order);
  const csv=await exportRows(page,table,config.kind);assert.deepEqual(csv.map(r=>r[config.id]),order);
  for(const r of csv){const original=rows.find(x=>String(x[config.id])===r[config.id]);for(const field of ['imports','exports','balance','total_trade_value'])if(`${field}_usd`in r){assert.equal(r[`${field}_usd`],original[field].value===null?'':String(original[field].value));assert.equal(r[`${field}_status`],original[field].status);}}
  assertCharts(await chartPaths(page),initialCharts);assert.deepEqual(await page.locator('.world-total-card').allTextContents(),totals);
  checks.push({table:config.kind,column:key,direction,rows:order.length,first:order.slice(0,3),last:order.slice(-3),csvRows:csv.length});
 }
 return {directions:Object.keys(config.columns).length*2,rows:rows.length};
}));
test('sort keyboard state survives refresh Back and year changes; charts and group selection stay stable',()=>withPage(async page=>{
 await go(page,'partner/7530?year=2013&section=I');const groups=page.locator('.partner-groups-table');await setSort(groups,'Imports','asc',true);const firstUrl=page.url();await setSort(groups,'Imports','desc',true);await page.goBack({waitUntil:'networkidle'});assert.equal(page.url(),firstUrl);assert.equal(await header(groups,'Imports').getAttribute('aria-sort'),'ascending');await page.reload({waitUntil:'networkidle'});assert.equal(await header(groups,'Imports').getAttribute('aria-sort'),'ascending');
 await page.getByRole('button',{name:/^View chapters in section XVI:/}).click();assert.equal(new URL(page.url()).searchParams.get('section'),'XVI');assert.deepEqual((await rowIds(page.locator('.partner-chapters-table'),'chapters')).sort(),['84','85']);
 await page.locator('#year-select').selectOption('2025');assert.equal(new URL(page.url()).searchParams.get('groups_dir'),'asc');await page.waitForFunction(()=>document.querySelector('#year-select').value==='2025');assert.deepEqual(await rowIds(groups,'groups'),expected(annualRows('groups','7530',2025),configs.find(x=>x.kind==='groups'),'imports','asc'));
 await page.locator('#year-select').selectOption('all');assert.equal(new URL(page.url()).searchParams.get('groups_dir'),'asc');await page.reload({waitUntil:'networkidle'});assert.equal(new URL(page.url()).searchParams.get('year'),'all');assert.equal(await header(groups,'Imports').getAttribute('aria-sort'),'ascending');
}));
test('home sorting preserves financial rank and full export under search and visible limit',()=>withPage(async page=>{
 await go(page,'?year=2013');const table=page.locator('.home-ranking-table');await setSort(table,'Imports','asc');assert.equal(await table.locator('tbody tr').count(),25);await page.getByRole('button',{name:/Show all/}).click();assert.match(await page.getByRole('button',{name:/Show first 25/i}).innerText(),/first 25/i);await page.getByRole('button',{name:/Show first 25/i}).click();await page.locator('#partner-search').fill('7530');assert.equal(await table.locator('tbody tr').count(),1);const params=new URL(page.url()).searchParams,metric=params.get('rank')??'total_trade_value';const rows=annualRows('home');const financial=expectedOrder(rows,r=>flowValue(r,metric),r=>r.code,'desc');assert.equal((await table.locator('tbody tr > :first-child').innerText()).trim(),String(financial.findIndex(r=>r.code==='7530')+1));const csv=await exportRows(page,table,'home');assert.equal(csv.length,236);assert.deepEqual(csv.map(r=>r.code),expected(rows,configs[0],'imports','asc',metric));
}));
test('rank dropdown changes selected sort; independent table choices survive Hub navigation',()=>withPage(async page=>{
 for(const config of configs.slice(0,2)){await go(page,config.route);const table=page.locator(config.selector);await setSort(table,'Imports','asc');await page.locator(config.kind==='home'?'#rank-field':'#section-rank-field').selectOption('exports');const params=new URL(page.url()).searchParams;assert.equal(params.get('rank'),'exports');assert.equal(params.get(`${config.kind}_sort`),'exports');assert.equal(params.get(`${config.kind}_dir`),'desc');assert.equal(await header(table,'Exports').getAttribute('aria-sort'),'descending');}
 await go(page,'?year=2013&home_sort=imports&home_dir=asc&section_sort=exports&section_dir=desc');const nav=page.getByRole('navigation',{name:'Main navigation'});await nav.getByRole('link',{name:'Hub',exact:true}).click();await page.locator('a[href*="section/XVI?"]').click();assert.equal(await header(page.locator('.section-page table'),'Exports').getAttribute('aria-sort'),'descending');assert.equal(new URL(page.url()).searchParams.get('rank'),'exports');await nav.getByRole('link',{name:'Explore',exact:true}).click();assert.equal(await header(page.locator('.home-ranking-table'),'Imports').getAttribute('aria-sort'),'ascending');assert.equal(new URL(page.url()).searchParams.get('rank'),'imports');
}));
test('invalid sort keys and directions normalize with visible explanation',()=>withPage(async page=>{
 await go(page,'partner/7530?year=2013&groups_sort=invalid&groups_dir=up&years_sort=year&years_dir=sideways');const params=new URL(page.url()).searchParams;assert.equal(params.has('groups_sort'),false);assert.equal(params.has('groups_dir'),false);assert.equal(params.has('years_dir'),false);assert.match(await page.locator('.url-notice').innerText(),/sort.*not available/i);assert.equal(await header(page.locator('.partner-years-table'),'Year').getAttribute('aria-sort'),'ascending');
}));
test('sort controls preserve centered figures, nowrap years and contained mobile scrolling',()=>withPage(async page=>{
 for(const width of [1280,390]){await page.setViewportSize({width,height:900});for(const config of configs){await go(page,config.route);const table=page.locator(config.selector);await setSort(table,'Imports','asc',true);if(config.kind==='groups')await page.getByRole('checkbox',{name:'Show exact USD in tables'}).check();
  const geometry=await table.evaluate(t=>{const heads=[...t.querySelectorAll('thead th')],cells=[...t.querySelector('tbody tr').children];return heads.map((h,i)=>{const button=h.querySelector('button'),label=(()=>{const r=document.createRange();r.selectNodeContents(button.querySelector('span:nth-child(2)'));return r.getBoundingClientRect();})(),hb=h.getBoundingClientRect(),c=cells[i],cb=c.getBoundingClientRect(),money=c.querySelector('.money-cell');return {label:button.textContent,headerAlign:getComputedStyle(h).textAlign,bodyAlign:getComputedStyle(c).textAlign,labelCenterDelta:Math.abs(label.x+label.width/2-hb.x-hb.width/2),columnDelta:Math.abs(hb.x+hb.width/2-cb.x-cb.width/2),buttonWidth:button.getBoundingClientRect().width,buttonHeight:button.getBoundingClientRect().height,nowrap:money?getComputedStyle(money).whiteSpace:null};});});
  for(const c of geometry){assert.ok(c.columnDelta<1);assert.ok(c.buttonHeight>=44);if(c.nowrap)assert.equal(c.nowrap,'nowrap');if(c.headerAlign==='center')assert.ok(c.labelCenterDelta<1,JSON.stringify({table:config.kind,viewport:width,...c}));}
  for(const c of geometry.filter(c=>/^(Rank|Year|Imports|Exports|Balance|Total trade)/.test(c.label))){assert.equal(c.headerAlign,'center');assert.equal(c.bodyAlign,'center');}
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const region=table.locator('..');if(width===390){assert.ok(await region.evaluate(e=>e.scrollWidth>e.clientWidth));await region.evaluate(e=>e.scrollLeft=e.scrollWidth);assert.ok(await region.evaluate(e=>e.scrollLeft>0));await region.evaluate(e=>e.scrollLeft=0);}
  await region.evaluate(e=>e.scrollIntoView({block:'start'}));const box=await region.boundingBox();await page.screenshot({path:path.join(output,`${config.kind}-${width}.png`),clip:{x:box.x,y:box.y,width:box.width,height:Math.min(box.height,360,900-box.y)}});
 }
 }
 await page.setViewportSize({width:320,height:900});await go(page,'partner/1220?year=all');await page.getByRole('checkbox',{name:'Show exact USD in tables'}).check();const yearly=page.locator('.partner-years-table');await setSort(yearly,'Imports','asc');assert.ok(await yearly.locator('tbody tr > :first-child').evaluateAll(cells=>cells.every(c=>{const r=document.createRange();r.selectNodeContents(c);return new Set([...r.getClientRects()].map(rect=>Math.round(rect.top))).size===1;})));return {tables:5,widths:2,extra320YearCheck:true};
}));
try{const results=await runAll();console.log(formatResults(results));fs.writeFileSync(path.join(output,process.env.TABLE_RUN?`results-${process.env.TABLE_RUN}.json`:'results.json'),JSON.stringify({target:live?'production':'local',index_sha256:createHash('sha256').update(fs.readFileSync('dist/index.html')).digest('hex'),results,checks,errors,input_sha256:hashes},null,2)+'\n');process.exitCode=results.some(r=>r.status!=='PASS')?1:0;}finally{await browser.close();await server?.stop();}
