/* eslint-disable */
/**
 * This file was automatically generated from schema/*.schema.json.
 * Do not edit this file directly. Run `npm run gen:types` to regenerate it.
 */

export type Partner = {
  [k: string]: unknown;
} & {
  /**
   * Census CTY_CODE (4 digits) or EU for the computed aggregate. Only kind aggregate may use a non-numeric id. The world row - is never a partner.
   */
  code: string;
  name: string;
  kind: 'country' | 'territory' | 'special' | 'aggregate';
  iso3: string | null;
  /**
   * world-atlas numeric ISO 3166-1 id
   */
  map_feature_id: number | null;
  include_in_world_reconciliation: boolean;
  /**
   * first year observed in any flow
   */
  valid_from: number | null;
  /**
   * last year observed in any flow
   */
  valid_to: number | null;
  /**
   * unresolved never appears in published data
   */
  resolution: 'approved' | 'excluded';
  resolution_note: string | null;
};
/**
 * observed requires an integer and null reason. confirmed_zero requires 0 and a reason citing the source evidence. absent and not_applicable require null and a reason. fetch_failed never appears in published data.
 */
export type FlowValue = {
  status: 'observed' | 'confirmed_zero' | 'absent' | 'not_applicable';
  /**
   * Integer USD or null
   */
  value: number | null;
  reason: string | null;
} & (
  | {
      status?: 'observed';
      value?: number;
      reason?: null;
    }
  | {
      status?: 'confirmed_zero';
      value?: 0;
      reason?: string;
    }
  | {
      status?: 'absent';
      value?: null;
      reason?: string;
    }
  | {
      status?: 'not_applicable';
      value?: null;
      reason?: string;
    }
);
/**
 * balance and total_trade_value. observed only when both inputs are observed or confirmed_zero; otherwise absent with a reason naming the missing input.
 */
export type DerivedValue = {
  status: 'observed' | 'absent';
  value: number | null;
  reason: string | null;
} & (
  | {
      status?: 'observed';
      value?: number;
      reason?: null;
    }
  | {
      status?: 'absent';
      value?: null;
      reason?: string;
    }
);

/**
 * This interface was referenced by `GeneratedRoot`'s JSON-Schema
 * via the `definition` "Meta".
 */
export interface Meta {
  schema_version: '1.0.0';
  /**
   * UTC acquisition start compact timestamp, then the first 12 hex chars of the raw manifest sha256. Deterministic under rebuild.
   */
  snapshot_id: string;
  code_commit: string;
  model_ids: {
    orchestrator: string;
    subagents: string;
  };
  raw_manifest_hash: string;
  /**
   * acquisition start, UTC; reused verbatim on rebuild
   */
  fetched_at: string;
  /**
   * observed LAST_UPDATE literal per endpoint; returns 0 as of 2026-09 and is not verified as a date
   */
  source_last_update: {
    imports: string;
    exports: string;
    verified: false;
  };
  source_fingerprint: {
    latest_period: {
      imports: string;
      exports: string;
    };
    /**
     * sha256 of the sorted JSON of world-total _YR values for every verified year, both flows
     */
    world_totals_sha256: string;
    before_equals_after: true;
  };
  latest_period: string;
  documented_availability: {
    from_year: number;
    source: string;
  };
  verified_availability: {
    from_year: number;
    to_year: number;
    probes_file: string;
  };
  configured_coverage: {
    start_year: number;
    end_year: number;
    years: number[];
  };
  eu_definition: string;
  country_map_version: string;
  hs_sections_version: string;
  notes: string[];
}
/**
 * This interface was referenced by `GeneratedRoot`'s JSON-Schema
 * via the `definition` "Partners".
 */
export interface Partners {
  schema_version: '1.0.0';
  /**
   * UTC acquisition start compact timestamp, then the first 12 hex chars of the raw manifest sha256. Deterministic under rebuild.
   */
  snapshot_id: string;
  /**
   * every code observed in any year or flow plus EU, sorted by code, each approved or excluded
   */
  partners: Partner[];
}
/**
 * This interface was referenced by `GeneratedRoot`'s JSON-Schema
 * via the `definition` "PartnerFile".
 */
export interface PartnerFile {
  schema_version: '1.0.0';
  /**
   * UTC acquisition start compact timestamp, then the first 12 hex chars of the raw manifest sha256. Deterministic under rebuild.
   */
  snapshot_id: string;
  partner: Partner;
  /**
   * one entry per configured year, sorted by year
   */
  years: {
    year: number;
    imports: FlowValue;
    exports: FlowValue;
    balance: DerivedValue;
    total_trade_value: DerivedValue;
    /**
     * EU membership-change note on 2013 and 2020 for EU; null otherwise
     */
    note: string | null;
  }[];
  /**
   * one entry per configured year, sorted by year
   */
  sections: {
    year: number;
    /**
     * every group in hs_sections, sorted by group order
     */
    groups: {
      section_id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      imports: FlowValue;
      exports: FlowValue;
      total_trade_value: DerivedValue;
      /**
       * every chapter in the valid chapter set for that flow and year, sorted by chapter
       */
      chapters: Chapter2[];
    }[];
  }[];
}
export interface Chapter2 {
  chapter: string;
  description: string | null;
  imports: FlowValue;
  exports: FlowValue;
  total_trade_value: DerivedValue;
}
/**
 * world holds the separately fetched world totals, not a sum of rows
 *
 * This interface was referenced by `GeneratedRoot`'s JSON-Schema
 * via the `definition` "Summary".
 */
export interface Summary {
  schema_version: '1.0.0';
  /**
   * UTC acquisition start compact timestamp, then the first 12 hex chars of the raw manifest sha256. Deterministic under rebuild.
   */
  snapshot_id: string;
  year: number;
  world: FlowsWithDerived;
  /**
   * approved partners only, sorted by code; includes EU with kind aggregate
   */
  partners: {
    /**
     * Census CTY_CODE (4 digits) or EU for the computed aggregate. The world row - is never a partner.
     */
    code: string;
    name: string;
    kind: 'country' | 'territory' | 'special' | 'aggregate';
    include_in_world_reconciliation: boolean;
    imports: FlowValue;
    exports: FlowValue;
    balance: DerivedValue;
    total_trade_value: DerivedValue;
  }[];
}
export interface FlowsWithDerived {
  imports: FlowValue;
  exports: FlowValue;
  balance: DerivedValue;
  total_trade_value: DerivedValue;
}
/**
 * This interface was referenced by `GeneratedRoot`'s JSON-Schema
 * via the `definition` "Section".
 */
export interface Section {
  schema_version: '1.0.0';
  /**
   * UTC acquisition start compact timestamp, then the first 12 hex chars of the raw manifest sha256. Deterministic under rebuild.
   */
  snapshot_id: string;
  section: {
    id:
      | 'I'
      | 'II'
      | 'III'
      | 'IV'
      | 'V'
      | 'VI'
      | 'VII'
      | 'VIII'
      | 'IX'
      | 'X'
      | 'XI'
      | 'XII'
      | 'XIII'
      | 'XIV'
      | 'XV'
      | 'XVI'
      | 'XVII'
      | 'XVIII'
      | 'XIX'
      | 'XX'
      | 'XXI'
      | 'SPECIAL';
    name: string;
    chapters: string[];
  };
  /**
   * sorted by year
   */
  years: {
    year: number;
    /**
     * sums over the reconciliation universe only
     */
    universe: FlowsWithDerived;
    /**
     * approved partners including EU with kind aggregate, sorted by code; the UI ranks
     */
    partners: {
      /**
       * Census CTY_CODE (4 digits) or EU for the computed aggregate. The world row - is never a partner.
       */
      code: string;
      name: string;
      kind: 'country' | 'territory' | 'special' | 'aggregate';
      include_in_world_reconciliation: boolean;
      imports: FlowValue;
      exports: FlowValue;
      balance: DerivedValue;
      total_trade_value: DerivedValue;
    }[];
  }[];
}
/**
 * This interface was referenced by `GeneratedRoot`'s JSON-Schema
 * via the `definition` "HsSections".
 */
export interface HsSections {
  version: string;
  source: {
    title: string;
    url: string;
    accessed: string;
  };
  /**
   * @minItems 22
   * @maxItems 22
   */
  groups: [
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    },
    {
      id:
        | 'I'
        | 'II'
        | 'III'
        | 'IV'
        | 'V'
        | 'VI'
        | 'VII'
        | 'VIII'
        | 'IX'
        | 'X'
        | 'XI'
        | 'XII'
        | 'XIII'
        | 'XIV'
        | 'XV'
        | 'XVI'
        | 'XVII'
        | 'XVIII'
        | 'XIX'
        | 'XX'
        | 'XXI'
        | 'SPECIAL';
      name: string;
      /**
       * @minItems 1
       */
      chapters: [string, ...string[]];
    }
  ];
  /**
   * valid chapter set observed per flow and year; derived from data, never hard-coded
   */
  chapter_sets: {
    imports: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[0-9]{4}$".
       */
      [k: string]: string[];
    };
    exports: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[0-9]{4}$".
       */
      [k: string]: string[];
    };
  };
}
