#!/usr/bin/env node
// Generates src/types/generated.ts from schema/*.schema.json.
// Deterministic: fixed file list, fixed order, no timestamps, no environment-dependent
// output. Agent D's CI test regenerates and diffs this file byte for byte.
//
// Approach: build one synthetic root JSON Schema whose "definitions" map each
// published file's schema to a clean PascalCase name, and whose $refs to
// common.schema.json resolve relative to schema/ (via the `cwd` option). Compiling
// this single combined document in one pass lets json-schema-to-typescript dedupe
// every shared common.schema.json definition (FlowValue, DerivedValue, Partner,
// Chapter2, Kind, ...) into one declaration instead of repeating it per file.

import { compile } from 'json-schema-to-typescript';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const schemaDir = path.join(rootDir, 'schema');
const outFile = path.join(rootDir, 'src', 'types', 'generated.ts');

// Fixed, sorted order. Keys become the generated TypeScript interface/type names.
const FILES = [
  ['Meta', 'meta.schema.json'],
  ['Partners', 'partners.schema.json'],
  ['PartnerFile', 'partner.schema.json'],
  ['Summary', 'summary.schema.json'],
  ['Section', 'section.schema.json'],
  ['HsSections', 'hs_sections.schema.json'],
];

async function readJson(file) {
  const raw = await fs.readFile(path.join(schemaDir, file), 'utf-8');
  return JSON.parse(raw);
}

function stripMeta(schema) {
  // Drop $schema/$id/title from the nested copy; the wrapping root schema carries
  // its own. Keeps output stable regardless of each file's own $id/title text.
  const { $schema, $id, title, ...rest } = schema;
  return rest;
}

async function main() {
  const definitions = {};
  for (const [name, file] of FILES) {
    definitions[name] = stripMeta(await readJson(file));
  }

  const rootSchema = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://us-trade-partners.local/schema/generated-root.json',
    title: 'GeneratedRoot',
    type: 'object',
    definitions,
  };

  const rawTs = await compile(rootSchema, 'GeneratedRoot', {
    cwd: schemaDir,
    bannerComment:
      '/* eslint-disable */\n' +
      '/**\n' +
      ' * This file was automatically generated from schema/*.schema.json.\n' +
      ' * Do not edit this file directly. Run `npm run gen:types` to regenerate it.\n' +
      ' */',
    style: { semi: true, singleQuote: true },
    unreachableDefinitions: true,
    additionalProperties: false,
    strictIndexSignatures: false,
    format: true,
    $refOptions: { dereference: { circular: false } },
  });

  // The wrapping GeneratedRoot type itself is not a published data shape;
  // drop its own declaration and keep only the six named file types plus every
  // common type they pulled in. GeneratedRoot has no properties of its own, so
  // compile() renders its body as either an empty `{}` or `{ [k: string]: unknown; }`
  // depending on the additionalProperties option; match the empty-body case first
  // so the non-greedy fallback never has to hunt past it into real content.
  const cleaned = rawTs.replace(
    /export interface GeneratedRoot \{\}\n\n?/,
    '',
  ).replace(
    /export interface GeneratedRoot \{\n(?:[\s\S]*?)\n\}\n\n?/,
    '',
  );

  await fs.mkdir(path.dirname(outFile), { recursive: true });
  await fs.writeFile(outFile, cleaned, 'utf-8');
  // eslint-disable-next-line no-console
  console.log(`[gen:types] wrote ${path.relative(rootDir, outFile)} (${cleaned.length} bytes)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
